name: Lab03 CI/CD with SSH Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Build Frontend
    - name: Build Frontend Docker Image
      working-directory: ./frontend
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest .

    # Build Backend
    - name: Build Backend Docker Image
      working-directory: ./backend
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-backend:latest .

    # Login to DockerHub
    - name: DockerHub Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Push Images
    - name: Push Frontend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest

    - name: Push Backend Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:latest

    # SSH Deploy Frontend to VM1
    - name: SSH Deploy Frontend (VM1)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM1_HOST }}
        username: ${{ secrets.VM1_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest
          docker stop frontend-container || true
          docker rm frontend-container || true
          docker run -d --name frontend-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest

    # SSH Deploy Backend to VM2
    - name: SSH Deploy Backend (VM2)
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM2_HOST }}
        username: ${{ secrets.VM2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
          docker stop backend-service || true
          docker rm backend-service || true
          docker run -d --name backend-service -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
